platform:
    - x86
    - x64

environment:
    matrix:
        - VSVER: 14

configuration:
    - plain
    - shared

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:TARGET="VC-WIN32"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:TARGET="VC-WIN64A"
        }
    - ps: >-
        If ($env:Configuration -Match "shared") {
            $env:SHARED=""
            $env:BUILD_SHARED="ON"
        } Else {
            $env:SHARED="no-shared"
            $env:BUILD_SHARED="OFF"
        }
    - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
    - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%

build_script:
- cmake -H. -B_builds -DCMAKE_INSTALL_PREFIX=install
- cmake --build _builds
- cmake -E env CTEST_OUTPUT_ON_FAILURE=1 cmake --build _builds --target RUN_TESTS
- cmake --build _builds --target install
