set(CPACK_PACKAGE_NAME "wdc")

#set(PACK_PACKAGE_VENDOR "")
set(CPACK_PACKAGE_CONTACT "designerror@yandex.ru")

set(CPACK_PACKAGE_VERSION_MAJOR 0)
set(CPACK_PACKAGE_VERSION_MINOR 9)
set(CPACK_PACKAGE_VERSION_PATCH 9)
set(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH})

set(CPACK_PACKAGE_DESCRIPTION_FILE ${CMAKE_CURRENT_SOURCE_DIR}/DESCRIPTION)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ WebDAV Client library")

if(WIN32 AND NOT UNIX)
	#set(CPACK_PACKAGE_FILE_NAME)
endif()

set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_CURRENT_SOURCE_DIR}/LICENSE)
set(CPACK_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README.md)


#set(CPACK_RPM_PACKAGE_ARCHITECTURE )
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP )

set(CPACK_RPM_PACKAGE_VENDOR )
set(CPACK_RPM_PACKAGE_URL "https://github.com/designerror/webdav-client-cpp")

set(CPACK_RPM_PACKAGE_REQUIRES "openssl-devel curl-devel pugixml-devel")
set(CPACK_RPM_CHANGELOG_FILE ${CMAKE_CURRENT_SOURCE_DIR}/ChangeLog.md)


set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://designerror.github.io/webdav-client-cpp")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.1")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libssl-dev libcurl4-openssl-dev libpugixml-dev")
